name: hexa
recipe: drupal9
config:
  php: '7.4'
  #composer_version: '2.0.7'
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  drush: true
  xdebug: true
  config:
      php: .vscode/php.ini
proxy:
  appserver:
    - hexa.lndo.site
services:
  appserver:
    build:
      - composer install
  #redis:
    #type: redis
    #portforward: true
