name: hexa
type: drupal9
docroot: web
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
mariadb_version: ""
mysql_version: "8.0"
use_dns_when_possible: true
composer_version: ""
web_environment: []

hooks:
  post-start:
    - exec: cd ~/bin && ./init.sh
